// Code generated by mockery v2.9.4. DO NOT EDIT.

package controller

import mock "github.com/stretchr/testify/mock"

// CntrInterface is an autogenerated mock type for the CntrInterface type
type MockCntrInterface struct {
	mock.Mock
}
