version: '3.2'

services:
  frontend:
    build:
      context: .
      args:
        API_PORT: $API_PORT
        LOG_PATH: $LOG_PATH
        NODE_NAME: $NODE_NAME
        NODE_DC: $NODE_DC
    ports:
      - "${API_PORT}:${API_PORT}"