version: '3.2'

services:
  frontend:
    build:
      context: .
    container_name: frontendService
    volumes:
      - ./logs/:/logs/
    ports:
      - "${API_PORT}:${API_PORT}"

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.1
    environment:
      LOGSTASH_INSTANCE_URL: $LOGSTASH_INSTANCE_URL
    container_name: filebeatService
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/logs/
    depends_on:
      - frontend