# https://www.docker.elastic.co/
FROM grafana/grafana:latest
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
ARG GF_INSTALL_IMAGE_RENDERER_PLUGIN=true