// Code generated by mockery v2.9.4. DO NOT EDIT.
package controller

import (
	amqp "github.com/streadway/amqp"

	datastructures "github.com/iamcathal/neo/services/crawler/datastructures"

	mock "github.com/stretchr/testify/mock"
)

// CntrInterface is an autogenerated mock type for the CntrInterface type
type MockCntrInterface struct {
	mock.Mock
}

// CallGetFriends provides a mock function with given fields: steamID
func (_m *MockCntrInterface) CallGetFriends(steamID string) (datastructures.Friendslist, error) {
	ret := _m.Called(steamID)

	var r0 datastructures.Friendslist
	if rf, ok := ret.Get(0).(func(string) datastructures.Friendslist); ok {
		r0 = rf(steamID)
	} else {
		r0 = ret.Get(0).(datastructures.Friendslist)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(steamID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CallGetPlayerSummaries provides a mock function with given fields: steamIDList
func (_m *MockCntrInterface) CallGetPlayerSummaries(steamIDList string) ([]datastructures.Player, error) {
	ret := _m.Called(steamIDList)

	var r0 []datastructures.Player
	if rf, ok := ret.Get(0).(func(string) []datastructures.Player); ok {
		r0 = rf(steamIDList)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datastructures.Player)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(steamIDList)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConsumeFromJobsQueue provides a mock function with given fields:
func (_m *MockCntrInterface) ConsumeFromJobsQueue() (<-chan amqp.Delivery, error) {
	ret := _m.Called()

	var r0 <-chan amqp.Delivery
	if rf, ok := ret.Get(0).(func() <-chan amqp.Delivery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan amqp.Delivery)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublishToJobsQueue provides a mock function with given fields: jobJSON
func (_m *MockCntrInterface) PublishToJobsQueue(jobJSON []byte) error {
	ret := _m.Called(jobJSON)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(jobJSON)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveFriendsListToDataStore provides a mock function with given fields: _a0
func (_m *MockCntrInterface) SaveFriendsListToDataStore(_a0 datastructures.UserDetails) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(datastructures.UserDetails) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(datastructures.UserDetails) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
