version: '3.7'

services:
  mongodb:
    hostname: mongo-main
    container_name: mongo-main
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    command: --auth --replSet myreplset --keyFile /mongoConfig/mykey.key --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
      - ./config:/mongoConfig
    networks:
      - mongonetwork
  
  mongodb_exporter:
    image: bitnami/mongodb-exporter:latest
    ports:
      - 9216:9216
    environment:
      MONGODB_URI: ${MONGO_CONNECT_URL}
    networks:
      - mongonetwork

networks:
  mongonetwork:
    driver: bridge

volumes:
  mongodb_data: