name: Build Datastore

on:
  push:
    paths:
      - 'services/datastore/**'
      - '!**.md'

jobs:
  build:
    name: Build datastore job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup go runtime
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create .env and move into endpoints/
      run: |
        touch .env
        echo ORG=${{ secrets.ORG }} >> .env
        echo SYSTEM_STATS_BUCKET_TOKEN=${{ secrets.BUCKET_TOKEN }} >> .env
        echo INFLUXDB_URL=${{ secrets.INFLUXDB_URL }} >> .env
        mv .env services/datastore/endpoints
        cat services/datastore/endpoints/.env

    - name: Build the module
      run: cd services/datastore && go build -v ./...

    - name: Run service tests
      run: cd services/datastore && go test -v ./...