name: Build Frontend

on:
  push:
    paths:
      - 'services/frontend/**'
      - '!**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build frontend job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup go runtime
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build the module
      run: cd services/frontend && go build -v ./...

    - name: Run service tests
      run: cd services/frontend && go test -v ./...