name: Deploy Frontend

on: workflow_dispatch

jobs:
  build:
    name: Deploy frontend job
    runs-on: [self-hosted, frontend]

    steps:
    - uses: actions/checkout@v2

    - name: Create .env file
      run: |
        touch .env
        echo STATIC_CONTENT_DIR_NAME=${{ secrets.FRONTEND_STATIC_CONTENT_DIR_NAME }} >> .env
        echo CRAWLER_INSTANCE=${{ secrets.FRONTEND_CRAWLER_INSTANCE }} >> .env
        echo DATASTORE_INSTANCE=${{ secrets.DATASTORE_INSTANCE }} >> .env
        

        echo API_PORT=${{ secrets.FRONTEND_API_PORT }} >> .env
        echo LOG_PATH=${{ secrets.FRONTEND_LOG_PATH }} >> .env
        echo NODE_NAME=${{ secrets.FRONTEND_NODE_NAME }} >> .env
        echo NODE_DC=${{ secrets.FRONTEND_NODE_DC }} >> .env
        echo SYSTEM_STATS_BUCKET=${{ secrets.SYSTEM_STATS_BUCKET }} >> .env
        echo SYSTEM_STATS_BUCKET_TOKEN=${{ secrets.SYSTEM_STATS_BUCKET_TOKEN }} >> .env
        echo ENDPOINT_LATENCIES_BUCKET=${{ secrets.ENDPOINT_LATENCIES_BUCKET }} >> .env
        echo ENDPOINT_LATENCIES_BUCKET_TOKEN=${{ secrets.ENDPOINT_LATENCIES_BUCKET_TOKEN }} >> .env
        echo ORG=${{ secrets.ORG }} >> .env
        echo INFLUXDB_URL=${{ secrets.INFLUXDB_URL }} >> .env
        echo LOGSTASH_INSTANCE_URL=${{ secrets.LOGSTASH_INSTANCE_URL }} >> .env
        echo AUTH_KEY=${{ secrets.AUTH_KEY }} >> .env
        echo SERVICE=frontend >> .env

        mv .env services/frontend
        cat services/frontend/.env
    
    - name: Update references from local to deployed datastore instance
      run: |
        cd services/frontend && sed -i "s|localhost:2590|${{ secrets.DATASTORE_INSTANCE}}|g" static/javascript/*.js 
        
    - name: Update references from local to deployed crawler instance
      run: |
        cd services/frontend && sed -i "s|localhost:2570|${{ secrets.CRAWLER_INSTANCE}}|g" static/javascript/*.js 
    

    - name: Deploy docker-compose service
      run: cd services/frontend && docker-compose up -d --build --force-recreate