name: Deploy Frontend

on: workflow_dispatch

jobs:
  build:
    name: Deploy frontend job
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Deploy docker-compose service
      run: docker-compose up -d