name: Deploy Frontend

on: workflow_dispatch

jobs:
  build:
    name: Deploy frontend job
    runs-on: [self-hosted, home]
    steps:
    - uses: actions/checkout@v2

    - name: Deploy docker-compose service
      run: cd services/frontend && docker-compose up -d