name: Deploy Frontend

on: workflow_dispatch

jobs:
  build:
    name: Deploy frontend job
    runs-on: [self-hosted, s1]
    steps:
    - uses: actions/checkout@v2

    - name: Deploy docker-compose service
      run: cd services/frontend && docker-compose up -d --build
      env:
        API_PORT: ${{ secrets.FRONTEND_API_PORT }}
        LOG_PATH: ${{ secrets.FRONTEND_LOG_PATH }}
        NODE_NAME: ${{ secrets.FRONTEND_NODE_NAME }}
        NODE_DC: ${{ secrets.FRONTEND_NODE_DC }}
        STATIC_CONTENT_DIR_NAME: ${{ secrets.FRONTEND_STATIC_CONTENT_DIR_NAME }}