name: Deploy Frontend

on: workflow_dispatch

jobs:
  build:
    name: Deploy frontend job
    runs-on: [self-hosted, s1]

    steps:
    - name: Update permissions for local repo directory
      run: |
        sudo chown -R ghrunner:ghrunner /home/github/actions-runner/_work/

    - uses: actions/checkout@v2

    - name: Create .env file
      run: |
        touch .env
        echo STATIC_CONTENT_DIR_NAME=${{ secrets.FRONTEND_STATIC_CONTENT_DIR_NAME }} >> .env
        echo CRAWLER_INSTANCE=${{ secrets.FRONTEND_CRAWLER_INSTANCE }} >> .env
        echo DATASTORE_URL=${{ secrets.DATASTORE_URL }} >> .env
        

        echo API_PORT=${{ secrets.FRONTEND_API_PORT }} >> .env
        echo LOG_PATH=${{ secrets.FRONTEND_LOG_PATH }} >> .env
        echo NODE_NAME=${{ secrets.FRONTEND_NODE_NAME }} >> .env
        echo NODE_DC=${{ secrets.FRONTEND_NODE_DC }} >> .env
        echo SYSTEM_STATS_BUCKET=${{ secrets.SYSTEM_STATS_BUCKET }} >> .env
        echo SYSTEM_STATS_BUCKET_TOKEN=${{ secrets.SYSTEM_STATS_BUCKET_TOKEN }} >> .env
        echo ENDPOINT_LATENCIES_BUCKET=${{ secrets.ENDPOINT_LATENCIES_BUCKET }} >> .env
        echo ENDPOINT_LATENCIES_BUCKET_TOKEN=${{ secrets.ENDPOINT_LATENCIES_BUCKET_TOKEN }} >> .env
        echo ORG=${{ secrets.ORG }} >> .env
        echo INFLUXDB_URL=${{ secrets.INFLUXDB_URL }} >> .env
        echo LOGSTASH_INSTANCE_URL=${{ secrets.LOGSTASH_INSTANCE_URL }} >> .env

        mv .env services/frontend
        cat services/frontend/.env

    - name: Deploy docker-compose service
      run: cd services/frontend && docker-compose up -d --build